# Generated by Django 4.0.5 on 2022-10-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fourth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_abc2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=70)),
            ],
        ),
        migrations.AlterField(
            model_name='student_abc',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
